NUMPY STARTS FROM HERE

At the core of the numpy package,is the ndarray object.This Encapsulates N-Dimensional Arrays Of Homogeneous Data Types 
it is c library made for python

Numpy Arrays Vs Python Sequences
>It has a fixed size.
>The elements in numpy array has required to have same data type and thus have same size in memory.
>Numpy Arrays Facilitate Advanced Mathematical Operations.
>All other library are directly or indirectly based on numpy.

Creating Numpy Arrays

In [ ]:
import numpy as np
#1d array
a=np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
#2d array
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
#3d array
a=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a)
print(type(a))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


In [7]:
#float array
a=np.array([1, 2, 3], dtype=float)
print(a)
print(type(a))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [9]:
#np.arange
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
#np with reshape
a=np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#np.ones used to create a ones matrix
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#np.zeroes used to create a zero matrix
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#np.random creates a random matrix
np.random.random((3,3))

array([[0.04165011, 0.8540543 , 0.31850828],
       [0.10190693, 0.73286173, 0.45319931],
       [0.5548541 , 0.7922003 , 0.19349373]])

In [20]:
#np .linspace used to create a sequence of numbers in a given range creates number at equal intervals
a=np.linspace(-10,10,10)
#.linspace(start,stop,steps)
print(a)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [22]:
#np.identity used to create a identity matrix
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Various Method To Create Matrix Or Arrays

Arrays Attributes 

In [23]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [24]:
#ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
#shape
a1.shape
#1d array

(10,)

In [28]:
a2.shape
#2d array

(3, 4)

In [29]:
a3.shape
#3d array


(2, 2, 2)

(a,b,c)
3d array consist of bXc matrix 
a represent number of bXc matrix

In [31]:
#size
a1.size

10

In [33]:
#itemsize - size of each element in bytes
a1.itemsize

4

In [34]:
#dtype
a1.dtype

dtype('int32')