## NUMPY TRICKS ##

>RETURN A SORTED COPY OF AN ARRAY

In [2]:
#code
import numpy as np
a=np.random.randint(1,100,15)
a
np.sort(a)#sorts the array in ascending order
#for descending order
#np.sort(a)[::-1]

array([14, 17, 19, 19, 28, 30, 37, 49, 56, 67, 69, 71, 78, 93, 93],
      dtype=int32)

In [4]:
b= np.random.randint(1,100,24).reshape(6,4)
b
np.sort(b,axis=0)#sorts the array in ascending order columnwise
#for descending order
#np.sort(b)[::-1]

array([[ 9,  7, 15,  6],
       [46, 20, 37, 18],
       [48, 23, 54, 37],
       [65, 35, 69, 59],
       [65, 77, 85, 86],
       [97, 99, 85, 99]], dtype=int32)

>np.append

>appends values at end of array


In [23]:
np.append(a,200)

array([ 68,  74,  85,  40,  19,  61,  89,  82,  71,  87,  25,  70,  35,
        33,  33, 200])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)#adding 1 in last column

array([[40., 33., 72., 51.,  1.],
       [80., 12., 18., 86.,  1.],
       [68., 93., 48., 31.,  1.],
       [50., 93., 39., 76.,  1.],
       [19., 97., 20., 96.,  1.],
       [18., 77., 93., 39.,  1.]])

>np.concatenate

>concatenate a sequence of arrays along an existing axis

In [ ]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
np.concatenate((c,d),axis=0)#concatenates row wise
np.concatenate((c,d),axis=1)#concatenates column wise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

>np.unique

we can get the unique values from an array

In [16]:
e=np.array([1,1,2,2,3,3,4,4,5,5])
np.unique(e)

array([1, 2, 3, 4, 5])

>np.expand_dims

we can expand the dimensions of an array

In [21]:
np.expand_dims(a, axis=1)

array([[68],
       [74],
       [85],
       [40],
       [19],
       [61],
       [89],
       [82],
       [71],
       [87],
       [25],
       [70],
       [35],
       [33],
       [33]], dtype=int32)

>np.where

The Function returns the indices of elements in array

In [25]:
a
np.where(a>50)

(array([ 0,  1,  2,  5,  6,  7,  8,  9, 11]),)

In [27]:
#replace all values greater than 50 with 0
np.where(a>50,0,a)

array([ 0,  0,  0, 40, 19,  0,  0,  0,  0,  0, 25,  0, 35, 33, 33],
      dtype=int32)

>np.argmax

returns the indices of the max element of the array in a particular axis

In [28]:
np.argmax(a)

np.int64(6)

In [30]:
np.argmax(b,axis=1)

array([2, 3, 1, 1, 1, 2])

>np.argmin

Does Opposite Work Of Argmax

In [31]:
np.argmin(a)

np.int64(4)

In [32]:
np.argmin(b,axis=0)

array([5, 1, 1, 2])

Day 2 Of Numpy Tricks

>np.cumsum

Gives The Cumulative Sum Of The Array In A Given Axis

In [3]:
a
np.cumsum(a)

array([ 67, 123, 153, 170, 189, 258, 272, 350, 443, 514, 563, 600, 619,
       712, 740])

In [6]:
b
np.cumsum(b,axis=0)

array([[ 65,   7,  69,  18],
       [113,  27, 106, 117],
       [122,  62, 160, 203],
       [219, 161, 175, 240],
       [265, 238, 260, 299],
       [330, 261, 345, 305]])

>np.cumprod

In [7]:
a
np.cumprod(a)

array([                  67,                 3752,               112560,
                    1913520,             36356880,           2508624720,
                35120746080,        2739418194240,      254765892064320,
          18088378336566720,   886330538491769280, -4099258223223639872,
       -4098929946410951104,  6181140531682131264,  7051238223713710848])

>np.percentile
compute the nth percentile of the given data

In [9]:
a
np.percentile(a,100)

np.float64(93.0)

>np.histogram 
gives the frequency chart of the given data in an array

In [10]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 4, 1, 2, 1, 1, 2, 2, 0, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

>np.corrcoef gives returns pearson_moment correlation coefficients

In [11]:
salary=np.array([10000,20000,30000,40000,50000])
experience=np.array([0,1,2,3,4])
np.corrcoef(salary,experience)

array([[1., 1.],
       [1., 1.]])

>np.isin

we can search multiple item in an array

In [17]:
items=np.array([10,20,30,40,50,60,70,80,90,100])

a[np.isin(a,items)]

array([30], dtype=int32)

>np.flip

reverses the order of array elements preserving the shape of array

In [19]:
np.flip(b,axis=0)

array([[65, 23, 85,  6],
       [46, 77, 85, 59],
       [97, 99, 15, 37],
       [ 9, 35, 54, 86],
       [48, 20, 37, 99],
       [65,  7, 69, 18]], dtype=int32)

>np.put

In [21]:
a
np.put(a,[0,2,4],True)
print(a)

[ 1 56  1 17  1 69 14 78 93 71 49 37 19 93 28]


>np.delete

In [22]:
np.delete(a,0)

array([56,  1, 17,  1, 69, 14, 78, 93, 71, 49, 37, 19, 93, 28],
      dtype=int32)

# SET FUNCTIONS #
  .np.union1d

  .np.intersect1d

  .np.setdiff1d

  .np.setexor1d
  
  .np.in1d

In [23]:
m=np.array([1,2,3,4,5])
n=np.array([6,7,8,9,10])
np.intersect1d(m,n)

array([], dtype=int64)

In [24]:
np.union1d(m,n)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.setdiff1d(m,n)

array([1, 2, 3, 4, 5])

In [26]:
np.setxor1d(m,n)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.in1d(m,1)

C:\Users\uzebk\AppData\Local\Temp\ipykernel_25260\3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

>np.clip

In [29]:
np.clip(a,a_min=30,a_max=70)

array([30, 56, 30, 30, 30, 69, 30, 70, 70, 70, 49, 37, 30, 70, 30],
      dtype=int32)

## NUMPY FINISHED ##