## NUMPY TRICKS ##

>RETURN A SORTED COPY OF AN ARRAY

In [ ]:
#code
import numpy as np
a=np.random.randint(1,100,15)
a
np.sort(a)#sorts the array in ascending order
#for descending order
#np.sort(a)[::-1]

array([19, 25, 33, 33, 35, 40, 61, 68, 70, 71, 74, 82, 85, 87, 89],
      dtype=int32)

In [ ]:
b= np.random.randint(1,100,24).reshape(6,4)
b
np.sort(b,axis=0)#sorts the array in ascending order columnwise
#for descending order
#np.sort(b)[::-1]

array([[18, 12, 18, 31],
       [19, 33, 20, 39],
       [40, 77, 39, 51],
       [50, 93, 48, 76],
       [68, 93, 72, 86],
       [80, 97, 93, 96]], dtype=int32)

>np.append

>appends values at end of array


In [23]:
np.append(a,200)

array([ 68,  74,  85,  40,  19,  61,  89,  82,  71,  87,  25,  70,  35,
        33,  33, 200])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)#adding 1 in last column

array([[40., 33., 72., 51.,  1.],
       [80., 12., 18., 86.,  1.],
       [68., 93., 48., 31.,  1.],
       [50., 93., 39., 76.,  1.],
       [19., 97., 20., 96.,  1.],
       [18., 77., 93., 39.,  1.]])

>np.concatenate

>concatenate a sequence of arrays along an existing axis

In [ ]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
np.concatenate((c,d),axis=0)#concatenates row wise
np.concatenate((c,d),axis=1)#concatenates column wise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

>np.unique

we can get the unique values from an array

In [16]:
e=np.array([1,1,2,2,3,3,4,4,5,5])
np.unique(e)

array([1, 2, 3, 4, 5])

>np.expand_dims

we can expand the dimensions of an array

In [21]:
np.expand_dims(a, axis=1)

array([[68],
       [74],
       [85],
       [40],
       [19],
       [61],
       [89],
       [82],
       [71],
       [87],
       [25],
       [70],
       [35],
       [33],
       [33]], dtype=int32)

>np.where

The Function returns the indices of elements in array

In [25]:
a
np.where(a>50)

(array([ 0,  1,  2,  5,  6,  7,  8,  9, 11]),)

In [27]:
#replace all values greater than 50 with 0
np.where(a>50,0,a)

array([ 0,  0,  0, 40, 19,  0,  0,  0,  0,  0, 25,  0, 35, 33, 33],
      dtype=int32)

>np.argmax

returns the indices of the max element of the array in a particular axis

In [28]:
np.argmax(a)

np.int64(6)

In [30]:
np.argmax(b,axis=1)

array([2, 3, 1, 1, 1, 2])

>np.argmin

Does Opposite Work Of Argmax

In [31]:
np.argmin(a)

np.int64(4)

In [32]:
np.argmin(b,axis=0)

array([5, 1, 1, 2])