Numpy Day 2 

Changing Datatype

In [ ]:
#astype
import numpy as np
a1=np.arange(9).reshape(3,3)
print(a1.dtype)
a2=a1.astype(np.float64)#convert to float
print(a2.dtype)

int32
float64


Array Operations

In [10]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [ ]:
#scalar operations
#arithmetic operations all arithmetic operations is possible on array happen element wise
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [17]:
#relational operations all relational operations is possible on array happen element wise
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#vector operations all vector operations happen element wise between two arrays when shape is same or compatible
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array Functions

In [19]:
a1=np.random.rand(3,3)
a1=np.round(a1*100)
a1

array([[87., 21., 28.],
       [63., 41., 23.],
       [90., 14., 67.]])

In [26]:
#max/min/sum/prod
#0->col 1->row
print(a1.max(axis=1))#tells the max in each row
print(a1.max(axis=0))#tells the max in each col
print(a1.min())#tells the min OF ALL ELEMENTS
print(a1.sum())#tells the sum OF ALL ELEMENTS
print(a1.prod())#tells the product OF ALL ELEMENTS

[87. 63. 90.]
[90. 41. 67.]
14.0
434.0
256563084793680.0


In [27]:
#mean/median/std/var
print(np.mean(a1))#tells the mean OF ALL ELEMENTS
print(np.median(a1))#tells the median OF ALL ELEMENTS
print(np.std(a1))#tells the standard dev OF ALL ELEMENTS
print(np.var(a1))#tells the variance OF ALL ELEMENTS

48.22222222222222
41.0
27.547041695485913
758.8395061728394


In [28]:
#trigonometric functions
print(np.sin(a1))

[[-0.82181784  0.83665564  0.27090579]
 [ 0.1673557  -0.15862267 -0.8462204 ]
 [ 0.89399666  0.99060736 -0.85551998]]


>IMPORTANT CONCEPT

In [29]:
#dot product we get the dot product of two arrays
#if the number of columns in the first matrix equals the number of rows in the second matrix. This is a crucial condition for matrix multiplication

a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
print(np.dot(a2,a3))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


![alt text](download.png)
>Happening of matrix multiplication

In [31]:
#log/exp
print(np.log(a1))
#print(np.exp(a1))

[[4.46590812 3.04452244 3.33220451]
 [4.14313473 3.71357207 3.13549422]
 [4.49980967 2.63905733 4.20469262]]


In [32]:
#rounding
print(np.round(a1))#rounds to nearest integer
print(np.ceil(a1))#rounds to nearest integer up
print(np.floor(a1))#rounds to nearest integer down

[[87. 21. 28.]
 [63. 41. 23.]
 [90. 14. 67.]]
[[87. 21. 28.]
 [63. 41. 23.]
 [90. 14. 67.]]
[[87. 21. 28.]
 [63. 41. 23.]
 [90. 14. 67.]]


Indexing And Slicing
>Important

>INDEXING

In [114]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [113]:
#indexing
print(a1[-1])#gives the last element
a2[1,2]#gives the element at 1st row 3rd col
#[m,n] m->row n->col

9


6

In [112]:
#indexing
a3
print(a3[1,0,1])
print(a3[0,0,0])
a3[1,1,0]
#[m,n,k] m->array number n->row k->col

10
0


12

>SLICING

In [ ]:
a1
a1[2:5]#gives the elements from 2 to 4
#[start:stop]#start is inclusive stop is exclusive

array([2, 3, 4])

In [87]:
a2
a2[0,:]#gives the 1st row colon denotes all col
a2[:,1]#gives the 2nd col colon denotes all row

array([1, 5, 9])

In [ ]:
a2
a2[1:,1:3]#gives the 2nd row to end and 2nd col to 3rd col
a2[::2,::3]#gives every 2nd row and every 3rd col
a2[::2,1::2]#gives every 2nd row and every 2nd col
a2[1::2,::3]#gives every 2nd row and 1st col
a2[0:2,1:]#gives the 1st and 2nd row and 2nd col to end

array([[1, 2, 3],
       [5, 6, 7]])

In [115]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [116]:
a3[0::2]#gives the 1st and 3rd array
a3[0::2,0::2]#gives the 1st and 3rd array and 1st and 3rd row
a3[0,1]#gives the 1st array and 2nd row
a3[1,:,1]#gives the 2nd array and 2nd col
a3[2,1:,1:]#gives the 3rd array and 2nd row to end and 2nd col to end
a3[0::2,0,0::2]#gives the 1st and 3rd array and 1st row and 1st and 3rd col

array([[ 0,  2],
       [18, 20]])

ITERATION

In [117]:
#iterating
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [118]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [119]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):#.nditer is used to iterate over an array
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


RESHAPING

>RESHAPE DONE

>TRANSPOSE

In [127]:
print(a2)
np.transpose(a2)#transposes the array
a2.T#EASY SYNTAX

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

>RAVEL

In [129]:
#ravel
a2
print(a2.ravel())#flattens the array means converts to 1D array

[ 0  1  2  3  4  5  6  7  8  9 10 11]


STACKING

>HORIZONTAL STACKING
![alt text](download-1.png)

In [130]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
print(np.hstack((a4,a5)))#stacks the arrays horizontally

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


>VERTICAL STACKING

![alt text](download-2.png)

In [131]:
print(np.vstack((a4,a5)))#stacks the arrays vertically

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


>SPLITTING 

>HORIZONTAL SPLITTING

![alt text](download-3.png)

In [132]:
a4
np.hsplit(a4,2)#splits the array horizontally

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

>VERTICAL SPLITTING

![alt text](download-4.png)

In [133]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

>NUMPY FUNDAMENTALS DONE